/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KEYPRESS_PB_H_INCLUDED
#define PB_KEYPRESS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _KeyPress {
    uint32_t key_id;
    uint32_t state;
    uint32_t ts;
} KeyPress;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define KeyPress_init_default                    {0, 0, 0}
#define KeyPress_init_zero                       {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define KeyPress_key_id_tag                      1
#define KeyPress_state_tag                       2
#define KeyPress_ts_tag                          3

/* Struct field encoding specification for nanopb */
#define KeyPress_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   state,             2) \
X(a, STATIC,   SINGULAR, UINT32,   ts,                3)
#define KeyPress_CALLBACK NULL
#define KeyPress_DEFAULT NULL

extern const pb_msgdesc_t KeyPress_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define KeyPress_fields &KeyPress_msg

/* Maximum encoded size of messages (where known) */
#define KEYPRESS_PB_H_MAX_SIZE                   KeyPress_size
#define KeyPress_size                            18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
