# generated by claude sonnet 4.6

import socket, struct

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
sock.bind(("0.0.0.0", 4210))

print("Listening on UDP 4210...")

seen_seqs = set()  # track seen sequence numbers to detect duplicates

while True:
    data, addr = sock.recvfrom(1024)

    if len(data) < 7:
        print("  Packet too short, skipping")
        continue

    ver, mtype, seq, dev_id, plen = struct.unpack_from(">BBHBH", data)
    payload = data[7:]
    print(f"  ver={ver} type=0x{mtype:02X} seq={seq} dev={dev_id}")

    if mtype == 0x01:  # KEY_PRESS
        # always ACK first, before anything else
        ack = struct.pack(">BBHBH", 1, 0x03, seq, dev_id, 0)
        sock.sendto(ack, addr)
        print(f"  ACK sent for seq={seq}")

        # duplicate check — same seq means retransmit, don't process twice
        if seq in seen_seqs:
            print(f"  Duplicate seq={seq}, ignoring")
            continue
        seen_seqs.add(seq)

        # parse TLV payload
        i = 0
        vals = {}
        while i + 1 < len(payload):
            tag, length = payload[i], payload[i + 1]
            vals[tag] = payload[i + 2: i + 2 + length]
            i += 2 + length

        key_id = vals.get(0x01, b'\x00')[0]
        state  = vals.get(0x02, b'\x00')[0]
        ts_raw = vals.get(0x03, b'\x00\x00\x00\x00')
        ts_ms  = struct.unpack(">I", ts_raw)[0] if len(ts_raw) == 4 else 0

        print(f"  KEY key_id={key_id} "
              f"state={'PRESSED' if state == 1 else 'RELEASED'} "
              f"ts={ts_ms}ms")

    elif mtype == 0x02:  # LIGHT_STATE — no ACK needed, periodic self-corrects
        i = 0
        vals = {}
        while i + 1 < len(payload):
            tag, length = payload[i], payload[i + 1]
            vals[tag] = payload[i + 2: i + 2 + length][0]
            i += 2 + length
        print(f"  LIGHT id={vals.get(1,'?')} R={vals.get(2,'?')} "
              f"G={vals.get(3,'?')} B={vals.get(4,'?')} bri={vals.get(5,'?')}")

    elif mtype == 0x03:  # ACK
        ack_seq = struct.unpack(">H", payload[:2])[0] if len(payload) >= 2 else -1
        print(f"  ACK for seq={ack_seq}")

    elif mtype == 0x04:  # HEARTBEAT — no ACK needed
        print(f"  HEARTBEAT")

    else:
        print(f"  Unknown type 0x{mtype:02X}, payload={payload.hex()}")